// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBranch(arg1) {
  return window['go']['repository']['Repository']['AddBranch'](arg1);
}

export function Commits(arg1) {
  return window['go']['repository']['Repository']['Commits'](arg1);
}

export function DelBranch(arg1, arg2) {
  return window['go']['repository']['Repository']['DelBranch'](arg1, arg2);
}

export function DelTag(arg1, arg2) {
  return window['go']['repository']['Repository']['DelTag'](arg1, arg2);
}

export function GetAllBranch() {
  return window['go']['repository']['Repository']['GetAllBranch']();
}

export function GetBranchHash(arg1) {
  return window['go']['repository']['Repository']['GetBranchHash'](arg1);
}

export function GetLocalBranch() {
  return window['go']['repository']['Repository']['GetLocalBranch']();
}

export function GitPull() {
  return window['go']['repository']['Repository']['GitPull']();
}

export function GitPush() {
  return window['go']['repository']['Repository']['GitPush']();
}

export function IsGitRepository(arg1) {
  return window['go']['repository']['Repository']['IsGitRepository'](arg1);
}

export function OpenFileManage() {
  return window['go']['repository']['Repository']['OpenFileManage']();
}

export function OpenTerminal() {
  return window['go']['repository']['Repository']['OpenTerminal']();
}

export function SwitchBranch(arg1) {
  return window['go']['repository']['Repository']['SwitchBranch'](arg1);
}

export function SwitchRepository(arg1) {
  return window['go']['repository']['Repository']['SwitchRepository'](arg1);
}

export function Tags() {
  return window['go']['repository']['Repository']['Tags']();
}
