// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBranch(arg1) {
  return window['go']['repository']['Repository']['AddBranch'](arg1);
}

export function Commit(arg1, arg2, arg3) {
  return window['go']['repository']['Repository']['Commit'](arg1, arg2, arg3);
}

export function Commits(arg1) {
  return window['go']['repository']['Repository']['Commits'](arg1);
}

export function CommitsLog() {
  return window['go']['repository']['Repository']['CommitsLog']();
}

export function CreateTag(arg1, arg2) {
  return window['go']['repository']['Repository']['CreateTag'](arg1, arg2);
}

export function CreateTagByCommitId(arg1, arg2) {
  return window['go']['repository']['Repository']['CreateTagByCommitId'](arg1, arg2);
}

export function DelBranch(arg1, arg2) {
  return window['go']['repository']['Repository']['DelBranch'](arg1, arg2);
}

export function DelTag(arg1, arg2) {
  return window['go']['repository']['Repository']['DelTag'](arg1, arg2);
}

export function DiffCommit(arg1, arg2) {
  return window['go']['repository']['Repository']['DiffCommit'](arg1, arg2);
}

export function DiffWorkStage(arg1) {
  return window['go']['repository']['Repository']['DiffWorkStage'](arg1);
}

export function DiscardChanges(arg1) {
  return window['go']['repository']['Repository']['DiscardChanges'](arg1);
}

export function FileStatus() {
  return window['go']['repository']['Repository']['FileStatus']();
}

export function GetAllBranch() {
  return window['go']['repository']['Repository']['GetAllBranch']();
}

export function GetBranchHash(arg1) {
  return window['go']['repository']['Repository']['GetBranchHash'](arg1);
}

export function GetCurrentBranch() {
  return window['go']['repository']['Repository']['GetCurrentBranch']();
}

export function GetLocalBranch() {
  return window['go']['repository']['Repository']['GetLocalBranch']();
}

export function GitPull() {
  return window['go']['repository']['Repository']['GitPull']();
}

export function GitPush() {
  return window['go']['repository']['Repository']['GitPush']();
}

export function IsRemoteRepo() {
  return window['go']['repository']['Repository']['IsRemoteRepo']();
}

export function MergeCommit(arg1, arg2) {
  return window['go']['repository']['Repository']['MergeCommit'](arg1, arg2);
}

export function MergeRebase(arg1, arg2) {
  return window['go']['repository']['Repository']['MergeRebase'](arg1, arg2);
}

export function MergeSquash(arg1, arg2) {
  return window['go']['repository']['Repository']['MergeSquash'](arg1, arg2);
}

export function OpenFileManage() {
  return window['go']['repository']['Repository']['OpenFileManage']();
}

export function OpenTerminal() {
  return window['go']['repository']['Repository']['OpenTerminal']();
}

export function PreMergeResult(arg1, arg2) {
  return window['go']['repository']['Repository']['PreMergeResult'](arg1, arg2);
}

export function RunCmdInRepository(arg1, arg2) {
  return window['go']['repository']['Repository']['RunCmdInRepository'](arg1, arg2);
}

export function SwitchBranch(arg1) {
  return window['go']['repository']['Repository']['SwitchBranch'](arg1);
}

export function SwitchRepository(arg1) {
  return window['go']['repository']['Repository']['SwitchRepository'](arg1);
}

export function Tags() {
  return window['go']['repository']['Repository']['Tags']();
}
