// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {repository} from '../models';

export function AddBranch(arg1:string):Promise<Error>;

export function Commit(arg1:string,arg2:string,arg3:Array<string>):Promise<string>;

export function Commits(arg1:string):Promise<Array<repository.Commit>>;

export function CreateTag(arg1:string,arg2:string):Promise<string>;

export function CreateTagByCommitId(arg1:string,arg2:string):Promise<string>;

export function DelBranch(arg1:string,arg2:boolean):Promise<string>;

export function DelTag(arg1:string,arg2:boolean):Promise<string>;

export function DiscardChanges(arg1:string):Promise<string>;

export function FileStatus():Promise<Array<repository.FileStatus>>;

export function GetAllBranch():Promise<Array<repository.Branch>>;

export function GetBranchHash(arg1:string):Promise<string>;

export function GetLocalBranch():Promise<Array<repository.Branch>>;

export function GitPull():Promise<string>;

export function GitPush():Promise<string>;

export function IsGitRepository(arg1:string):Promise<boolean>;

export function OpenFileManage():Promise<Error>;

export function OpenTerminal():Promise<Error>;

export function SwitchBranch(arg1:string):Promise<boolean>;

export function SwitchRepository(arg1:string):Promise<void>;

export function Tags():Promise<Array<repository.Tag>>;
