// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BindRepository(arg1) {
  return window['go']['main']['App']['BindRepository'](arg1);
}

export function FileStatus() {
  return window['go']['main']['App']['FileStatus']();
}

export function GetBranch() {
  return window['go']['main']['App']['GetBranch']();
}

export function IsGitRepository(arg1) {
  return window['go']['main']['App']['IsGitRepository'](arg1);
}

export function Log() {
  return window['go']['main']['App']['Log']();
}

export function MessageDialog(arg1, arg2) {
  return window['go']['main']['App']['MessageDialog'](arg1, arg2);
}

export function ReadJsonFile() {
  return window['go']['main']['App']['ReadJsonFile']();
}

export function SaveJsonFile(arg1) {
  return window['go']['main']['App']['SaveJsonFile'](arg1);
}

export function Sha1(arg1) {
  return window['go']['main']['App']['Sha1'](arg1);
}

export function SwitchBranch(arg1) {
  return window['go']['main']['App']['SwitchBranch'](arg1);
}

export function Tag() {
  return window['go']['main']['App']['Tag']();
}
