// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddBranch(arg1:string):Promise<Error>;

export function BindRepository(arg1:string):Promise<boolean>;

export function ChangesInfo(arg1:string):Promise<Array<main.DiffContent>>;

export function Clipboard(arg1:string):Promise<Error>;

export function Commit(arg1:string,arg2:string,arg3:Array<string>):Promise<string>;

export function CreateTag(arg1:string,arg2:string):Promise<Error>;

export function DelBranch(arg1:string,arg2:boolean):Promise<string>;

export function DelTag(arg1:string):Promise<Error>;

export function DiffCommit(arg1:string,arg2:string):Promise<main.DiffCommitInfo>;

export function DiffWorkStage(arg1:string):Promise<Array<main.DiffContent>>;

export function FileStatus():Promise<Array<main.Status>>;

export function GetBranch():Promise<Array<main.Branch>>;

export function GetLastCommit(arg1:string):Promise<string>;

export function GitPull():Promise<string>;

export function GitPush():Promise<string>;

export function IsGitRepository(arg1:string):Promise<boolean>;

export function Log():Promise<Array<main.Log>>;

export function MergeCommit(arg1:string,arg2:string):Promise<string>;

export function MergeRebase(arg1:string,arg2:string):Promise<string>;

export function MergeSquash(arg1:string,arg2:string):Promise<string>;

export function MessageDialog(arg1:string,arg2:string):Promise<void>;

export function OpenFileManage():Promise<Error>;

export function OpenTerminal():Promise<Error>;

export function PreMergeResult(arg1:string,arg2:string):Promise<main.MergeResult>;

export function ReadJsonFile():Promise<string>;

export function RepositoryPath():Promise<string>;

export function RunCmd(arg1:string):Promise<string>;

export function SaveJsonFile(arg1:string):Promise<Error>;

export function Sha256(arg1:string):Promise<string>;

export function SwitchBranch(arg1:string):Promise<boolean>;

export function Tag():Promise<Array<main.Tag>>;
