// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Clipboard(arg1) {
  return window['go']['main']['App']['Clipboard'](arg1);
}

export function IsGitRepository(arg1) {
  return window['go']['main']['App']['IsGitRepository'](arg1);
}

export function MessageDialog(arg1, arg2) {
  return window['go']['main']['App']['MessageDialog'](arg1, arg2);
}

export function ReadJsonFile() {
  return window['go']['main']['App']['ReadJsonFile']();
}

export function SaveJsonFile(arg1) {
  return window['go']['main']['App']['SaveJsonFile'](arg1);
}

export function Sha256(arg1) {
  return window['go']['main']['App']['Sha256'](arg1);
}
