// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BindRepository(arg1:string):Promise<boolean>;

export function FileStatus():Promise<Array<main.Status>>;

export function GetBranch():Promise<Array<main.Branch>>;

export function IsGitRepository(arg1:string):Promise<boolean>;

export function MessageDialog(arg1:string,arg2:string):Promise<void>;

export function Sha256(arg1:string):Promise<string>;

export function SwitchBranch(arg1:string):Promise<boolean>;

export function Tag():Promise<Array<main.Tag>>;
