// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Clipboard(arg1:string):Promise<void>;

export function IsGitRepository(arg1:string):Promise<boolean>;

export function MessageDialog(arg1:string,arg2:string):Promise<void>;

export function ReadJsonFile():Promise<string>;

export function SaveJsonFile(arg1:string):Promise<void>;

export function Sha256(arg1:string):Promise<string>;
